image:
  - Visual Studio 2019
environment:
  CMAKE_INSTALL_ROOT: C:\projects\cmake
  PACKAGE_INSTALL_ROOT: C:\projects\pir
  matrix:
    - build_name: mingw1120_64_qt6_7
      QTPATH: C:\Qt\6.8\mingw_64
      MINGW64: C:\Qt\Tools\mingw1310_64

install:
  - mkdir %CMAKE_INSTALL_ROOT%
  - mkdir %PACKAGE_INSTALL_ROOT%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - set PATH=%PATH%;%CMAKE_INSTALL_ROOT%;%QTPATH%\bin;%MINGW64%\bin
  - set CC=%MINGW64%\bin\gcc.exe
  - set CXX=%MINGW64%\bin\g++.exe

build_script:
# prepare
  - mkdir 3rdparty
  - choco install ninja
  - choco install gperf
  - cd 3rdparty
# install ECM
  - git clone -q https://invent.kde.org/frameworks/extra-cmake-modules.git
  - git rev-parse HEAD
  - cd extra-cmake-modules
  - cmake -G "Ninja" . -DCMAKE_INSTALL_PREFIX=%PACKAGE_INSTALL_ROOT% -DBUILD_TESTING=OFF
  - cmake --build . --target install
  - cd %APPVEYOR_BUILD_FOLDER%
# build kcodecs
  - git clone -q https://invent.kde.org/frameworks/kcodecs.git
  - cd kcodecs
  - cmake -G "Ninja" . -DCMAKE_INSTALL_PREFIX=%PACKAGE_INSTALL_ROOT% -DBUILD_TESTING=OFF
  - cmake --build . --target install
  - cd %APPVEYOR_BUILD_FOLDER%
# build taglib
  - git clone --recurse-submodules -q https://github.com/taglib/taglib.git
  - cd taglib  
  - cmake -G "Ninja" . -DCMAKE_INSTALL_PREFIX=%PACKAGE_INSTALL_ROOT% -DBUILD_SHARED_LIBS=ON
  - cmake --build . --target install
  - cd %APPVEYOR_BUILD_FOLDER%
  - tree %PACKAGE_INSTALL_ROOT% /f
# finally...
  - mkdir build
  - cd build
  - cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%PACKAGE_INSTALL_ROOT% -DCMAKE_INSTALL_PREFIX='%cd%'
  - cmake --build .
  - cmake --build . --target install
# fixme: I don't know how to NOT make the binary installed to the ./bin/ folder...
  - cd bin
  - windeployqt --verbose=2 --no-quick-import --no-translations --no-opengl-sw --compiler-runtime --no-system-d3d-compiler --multimedia .\pmusic.exe
  - xcopy /s %PACKAGE_INSTALL_ROOT%\bin %cd%
# for debug..
  - tree /f

artifacts:
  - path: build\bin
