environment:
  CMAKE_INSTALL_ROOT: C:\projects\cmake
  PACKAGE_INSTALL_ROOT: C:\projects\pir
  PKG_CONFIG_PATH: C:\projects\pir\lib\pkgconfig
  matrix:
    - build_name: mingw73_32_qt5_12_6
      QTPATH: C:\Qt\5.12.6\mingw73_32
      MINGW32: C:\Qt\Tools\mingw730_32

install:
  - mkdir %CMAKE_INSTALL_ROOT%
  - mkdir %PACKAGE_INSTALL_ROOT%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - set PATH=%PATH%;%CMAKE_INSTALL_ROOT%;%QTPATH%\bin;%MINGW32%\bin

build_script:
# prepare
  - mkdir 3rdparty
  - cinst ninja
  - cinst pkgconfiglite
# build taglib
  - cd 3rdparty
  - git clone -q https://github.com/taglib/taglib.git
  - cd taglib
  - cmake -G "Ninja" . -DCMAKE_INSTALL_PREFIX=%PACKAGE_INSTALL_ROOT% -DBUILD_SHARED_LIBS=ON
  - cmake --build .
  - cmake --build . --target install
  - cd %APPVEYOR_BUILD_FOLDER%
  - tree %PACKAGE_INSTALL_ROOT% /f
# finally...
  - mkdir build
  - cd build
  - cmake .. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_MAKE_PROGRAM=mingw32-make -DCMAKE_INSTALL_PREFIX='%cd%'
  - mingw32-make
  - mingw32-make install
# fixme: I don't know how to NOT make the binary installed to the ./bin/ folder...
  - cd bin
  - windeployqt --verbose=2 --no-quick-import --no-translations --no-opengl-sw --no-angle --no-system-d3d-compiler --release .\pmusic.exe
  - xcopy /s %PACKAGE_INSTALL_ROOT%\bin %cd%
# for debug..
  - tree /f

artifacts:
  - path: build\bin
